// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2Ju3FZJvwISPDTr9F5G85oRzmdYIY1o',
    appId: '1:16916775507:web:6a212a78bd1efea0143ca6',
    messagingSenderId: '16916775507',
    projectId: 'edunestapp-40732',
    authDomain: 'edunestapp-40732.firebaseapp.com',
    storageBucket: 'edunestapp-40732.firebasestorage.app',
    measurementId: 'G-E7J1XCRRV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJa0foDno0RO0Gych2hh8dOaV1noAtTC0',
    appId: '1:16916775507:android:8ec4ca982ddfd116143ca6',
    messagingSenderId: '16916775507',
    projectId: 'edunestapp-40732',
    storageBucket: 'edunestapp-40732.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCMaCQZVcPD-CHEnl4hWIaPc2l_bx9Hw',
    appId: '1:16916775507:ios:4020e856fc75395a143ca6',
    messagingSenderId: '16916775507',
    projectId: 'edunestapp-40732',
    storageBucket: 'edunestapp-40732.firebasestorage.app',
    iosBundleId: 'com.example.edunestApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCMaCQZVcPD-CHEnl4hWIaPc2l_bx9Hw',
    appId: '1:16916775507:ios:4020e856fc75395a143ca6',
    messagingSenderId: '16916775507',
    projectId: 'edunestapp-40732',
    storageBucket: 'edunestapp-40732.firebasestorage.app',
    iosBundleId: 'com.example.edunestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC2Ju3FZJvwISPDTr9F5G85oRzmdYIY1o',
    appId: '1:16916775507:web:e310907eb34c956f143ca6',
    messagingSenderId: '16916775507',
    projectId: 'edunestapp-40732',
    authDomain: 'edunestapp-40732.firebaseapp.com',
    storageBucket: 'edunestapp-40732.firebasestorage.app',
    measurementId: 'G-N7GRK2Q69P',
  );
}
