// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_IO90un8R5cxBVwmVqOIwL1MkS2B2WQ',
    appId: '1:977330281460:web:52cb1309b06092a083f7a1',
    messagingSenderId: '977330281460',
    projectId: 'todo-calendar-app-14bd3',
    authDomain: 'todo-calendar-app-14bd3.firebaseapp.com',
    storageBucket: 'todo-calendar-app-14bd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFjUVZwLCaNt5gAKZQuzZwFVAHmmKThV0',
    appId: '1:977330281460:android:b824cf7da4cdde0883f7a1',
    messagingSenderId: '977330281460',
    projectId: 'todo-calendar-app-14bd3',
    storageBucket: 'todo-calendar-app-14bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_e_YS8ra7lUHIvO26LjAfA1-F34ofQpY',
    appId: '1:977330281460:ios:516f9e159596343e83f7a1',
    messagingSenderId: '977330281460',
    projectId: 'todo-calendar-app-14bd3',
    storageBucket: 'todo-calendar-app-14bd3.firebasestorage.app',
    iosBundleId: 'com.example.todoCalendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_e_YS8ra7lUHIvO26LjAfA1-F34ofQpY',
    appId: '1:977330281460:ios:516f9e159596343e83f7a1',
    messagingSenderId: '977330281460',
    projectId: 'todo-calendar-app-14bd3',
    storageBucket: 'todo-calendar-app-14bd3.firebasestorage.app',
    iosBundleId: 'com.example.todoCalendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV_IO90un8R5cxBVwmVqOIwL1MkS2B2WQ',
    appId: '1:977330281460:web:7e83e14785fe707483f7a1',
    messagingSenderId: '977330281460',
    projectId: 'todo-calendar-app-14bd3',
    authDomain: 'todo-calendar-app-14bd3.firebaseapp.com',
    storageBucket: 'todo-calendar-app-14bd3.firebasestorage.app',
  );
}
